export const INSURANCE_INFORMATION_STATUS = {
    healthInsurance: {
        medicaid: 0,
        medicaidCardId: 2,
        familyHealthPlus: 4,
        familyHealthPlusCardId: 6,
        commercialInsurance: 8,
        personsCovered: 10,
        costOfPolicy: 12,
        endDateOfCoverage: 14,
        medicare: 16,
        medicalAssistance: 18,
        jobHealthInsurance: 20,
    },
    medicalExpense: {
        recentMedicalBill: 0,
        monthBilled: 2,
        oldMedicalBill: 4,
        pendingLawsuit: 6,
        injured: 8,
        recentMoveIn: 10,
        moveInState: 12,
        moveInCounty: 14,
    },
    deceasedOrLivingOutside: {
        parentDeceased: 0,
        parentLivingOutside: 2,
        parentPrivacy: 4,
        parentName: 6,
        parentDob: 8,
        parentStreet: 10,
        parentCity: 12,
        parentSsn: 14,
        spouseDeceased: 16,
        spouseLivingOutside: 18,
        spousePrivacy: 20,
        spouseName: 22,
        spouseDob: 24,
        spouseStreet: 26,
        spouseCity: 28,
        spouseSsn: 30,
    },
    healthPlan: {
        healthPlan: 0,
        healthPlanName: 2,
        currentDoctor: 4,
        preferredDoctor: 6,
        obGyn: 8,
    }
}